using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using Zapret2Pilot.Core.Primitives;
using Zapret2Pilot.Core.Profiles;
using Zapret2Pilot.Core.Results;
using Zapret2Pilot.Core.Runtime;

namespace Zapret2Pilot.Engine.Zapret2.Compiler;

/// <summary>
/// Pure, deterministic Zapret plan compiler. Given a fully-validated
/// <see cref="CompilationInputs"/>, the compiler produces a
/// <see cref="CompiledZapretPlan"/> populated with:
///
/// <list type="bullet">
///   <item>a content-addressed <see cref="RuntimePlanCacheKey"/> that
///         covers every <c>DEC-0011</c> input (profile document hash,
///         strategy pack hashes, hostlist fingerprints, runtime manifest
///         hash, compiler options, compiler version);</item>
///   <item>a <see cref="RuntimePlanId"/> derived deterministically from
///         that cache key;</item>
///   <item>the structured <c>winws2</c> argument tokens produced by
///         <see cref="WinwsArgumentBuilder"/>;</item>
///   <item>the <c>ArgsContent</c> written to <c>args.txt</c>;</item>
///   <item>a minimal placeholder <c>GeneratedConfigContent</c> (real
///         config generation is future work);</item>
///   <item>placeholder hostlist payloads (one per assignment) carrying
///         the relative path the materializer needs and an empty
///         <c>Content</c> &mdash; hostlist file contents are loaded by
///         the orchestrator, not the compiler.</item>
/// </list>
///
/// The compiler does NOT access the filesystem and does NOT launch any
/// process. It is intentionally a pure, hermetic component suitable for
/// focused unit tests.
/// </summary>
public sealed class ZapretPlanCompiler
{
    /// <summary>
    /// Placeholder command-line. The runtime kernel resolves the
    /// absolute path to <c>winws2.exe</c> at host level; the compiler
    /// emits this constant so callers can reason about the plan shape
    /// without coupling it to a filesystem layout.
    /// </summary>
    public const string CommandLinePlaceholder = "bin/winws2.exe";

    /// <summary>
    /// Minimal config header written to <c>generated.cfg</c> for now.
    /// Real config generation is future work.
    /// </summary>
    public const string GeneratedConfigPlaceholder = "# Generated by Zapret2Pilot\n";

    /// <summary>
    /// Compiles the supplied inputs into a fully populated
    /// <see cref="CompiledZapretPlan"/>.
    /// </summary>
#pragma warning disable CA1822 // Mark members as static; intentionally instance per the planned public API.
    public Result<CompiledZapretPlan> Compile(CompilationInputs inputs)
#pragma warning restore CA1822
    {
        if (inputs is null)
        {
            return Result.Failure<CompiledZapretPlan>(new ErrorInfo(
                "CompilerInputsMissing",
                "Compilation inputs are required.",
                ErrorSeverity.Error,
                ErrorCategory.Runtime));
        }

        try
        {
            RuntimePlanCacheKey cacheKey = ComputeCacheKey(inputs);
            RuntimePlanId planId = new(cacheKey.Value);

            WinwsArgumentBuilder.Result arguments =
                WinwsArgumentBuilder.Build(inputs.Definition.Strategies, inputs.Definition.Hostlists);

            List<CompiledZapretPlan.HostlistContent> hostlists = BuildHostlistPayloads(
                inputs.Definition.Hostlists);

            CompiledZapretPlan plan = new(
                generatedConfigContent: GeneratedConfigPlaceholder,
                argsContent: arguments.ArgsContent,
                hostlists: hostlists,
                id: planId,
                profileId: inputs.Definition.Id,
                commandLine: CommandLinePlaceholder,
                arguments: arguments.Tokens,
                cacheKey: cacheKey);

            return Result.Success(plan);
        }
        catch (Exception ex) when (ex is ArgumentException or ArgumentNullException)
        {
            // Deliberate exception filter: ArgumentException and
            // ArgumentNullException both map to the same
            // CompilerInputInvalid error code with identical message
            // shape. A single branch avoids duplicating the body, while
            // the filter still lets unrelated runtime exceptions
            // (e.g. OutOfMemoryException) propagate.
            return Result.Failure<CompiledZapretPlan>(new ErrorInfo(
                "CompilerInputInvalid",
                $"Compiler rejected the supplied inputs: {ex.Message}",
                ErrorSeverity.Error,
                ErrorCategory.Runtime));
        }
    }

    /// <summary>
    /// Computes the content-addressed cache key for the supplied
    /// inputs. Exposed as <c>internal</c> for white-box tests; the
    /// production entry point is <see cref="Compile"/>.
    /// </summary>
    internal static RuntimePlanCacheKey ComputeCacheKey(CompilationInputs inputs)
    {
        ArgumentNullException.ThrowIfNull(inputs, nameof(inputs));

        string canonical = BuildCanonicalInputString(inputs);

        byte[] bytes = Encoding.UTF8.GetBytes(canonical);
        byte[] hash = SHA256.HashData(bytes);
        string hex = Convert.ToHexString(hash).ToLowerInvariant();

        return new RuntimePlanCacheKey(hex);
    }

    private static string BuildCanonicalInputString(CompilationInputs inputs)
    {
        StringBuilder builder = new();

        builder.Append("profile=").Append(inputs.Definition.Id.Value).Append('\n');
        builder.Append("profile-doc-hash=").Append(inputs.ProfileDocumentHash).Append('\n');

        builder.Append("strategy-pack-hashes\n");
        AppendSortedKeyedHashes(builder, inputs.StrategyPackHashes, "  ");

        builder.Append("hostlist-fingerprints\n");
        AppendSortedKeyedHashes(builder, inputs.HostlistFingerprints, "  ");

        builder.Append("runtime-manifest-hash=").Append(inputs.RuntimeManifestHash).Append('\n');
        builder.Append("compiler-options\n").Append(inputs.Options.ToCanonicalString()).Append('\n');

        return builder.ToString();
    }

    private static void AppendSortedKeyedHashes<TKey>(
        StringBuilder builder,
        IEnumerable<KeyValuePair<TKey, string>> entries,
        string indent)
        where TKey : notnull
    {
        // Iterate the dictionary as KeyValuePairs so we never depend on
        // the relative order of an arbitrary implementation's Keys and
        // Values enumerators. The key's string representation is used
        // both for sorting and for emission so callers do not have to
        // pre-project.
        List<KeyValuePair<string, string>> pairs = entries
            .Select(kvp => new KeyValuePair<string, string>(
                kvp.Key.ToString() ?? string.Empty,
                kvp.Value))
            .ToList();

        pairs.Sort(static (left, right) => string.CompareOrdinal(left.Key, right.Key));

        foreach (KeyValuePair<string, string> pair in pairs)
        {
            builder.Append(indent).Append(pair.Key).Append('=').Append(pair.Value).Append('\n');
        }
    }

    private static List<CompiledZapretPlan.HostlistContent> BuildHostlistPayloads(
        IReadOnlyList<HostlistAssignment> hostlists)
    {
        ArgumentNullException.ThrowIfNull(hostlists);

        List<CompiledZapretPlan.HostlistContent> payloads =
            new(hostlists.Count);

        foreach (HostlistAssignment assignment in hostlists)
        {
            ArgumentNullException.ThrowIfNull(assignment, nameof(hostlists));
            // Hostlist file contents are loaded by the orchestrator, not
            // by the compiler. The materializer only needs the relative
            // path; the content is empty for now and will be filled in
            // by a later step that has access to the source files.
            payloads.Add(new CompiledZapretPlan.HostlistContent(
                relativePath: assignment.RelativePath,
                content: string.Empty));
        }

        return payloads;
    }

    /// <summary>
    /// Returns the executing assembly's informational version (e.g.
    /// <c>0.0.15+abc1234</c>) or a stable fallback when the metadata is
    /// missing. Exposed as <c>internal</c> so white-box tests can pin
    /// the compiler version.
    /// </summary>
    internal static string GetAssemblyInformationalVersion()
    {
        Assembly assembly = typeof(ZapretPlanCompiler).Assembly;
        AssemblyInformationalVersionAttribute? attribute = assembly
            .GetCustomAttribute<AssemblyInformationalVersionAttribute>();

        if (attribute is null || string.IsNullOrWhiteSpace(attribute.InformationalVersion))
        {
            return "0.0.0";
        }

        return attribute.InformationalVersion;
    }
}
